# Generated by Django 4.0.1 on 2022-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=2, upload_to='files/thumbnail'),
            preserve_default=False,
        ),
    ]
